services:
  mquery-server:
    build:
      context: .
    volumes:
      - ./conf-docker.json:/opt/mquery/conf-docker.json
      - corpora-data:/var/lib/manatee
      - split-data:/var/lib/manatee/split
    ports:
      - "8989:8989"
    networks:
      - redis
  
  mquery-worker:
    build:
      context: .
    command: "./mquery worker conf-docker.json"
    volumes:
      - ./conf-docker.json:/opt/mquery/conf-docker.json
      - corpora-data:/var/lib/manatee
      - split-data:/var/lib/manatee/split
    networks:
      - redis
    
  redis:
    image: redis:latest
    networks:
      - redis

volumes:
  split-data: {}
  corpora-data: {}

networks:
  redis: {}