// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/collocations/{corpusId}": {
            "get": {
                "description": "Calculate a defined collocation profile of a searched expression. Values are sorted in descending order by their collocation score.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Collocations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "An ID of a corpus to search in",
                        "name": "corpusId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The translated query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "An ID of a subcorpus",
                        "name": "subcorpus",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "absFreq",
                            "logLikelihood",
                            "logDice",
                            "minSensitivity",
                            "mutualInfo",
                            "mutualInfo3",
                            "mutualInfoLogF",
                            "relFreq",
                            "tScore"
                        ],
                        "type": "string",
                        "default": "logDice",
                        "description": "a collocation measure",
                        "name": "measure",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "left range for candidates searching; values must be greater or equal to 1 (1 stands for words right before the searched term)",
                        "name": "srchLeft",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "right range for candidates searching; values must be greater or equal to 1 (1 stands for words right after the searched term)",
                        "name": "srchRight",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 3,
                        "description": " the minimum frequency that a collocate must have in the searched range.",
                        "name": "minCollFreq",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "maximum number of result items",
                        "name": "maxItems",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/results.Collocations"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "mango.GoCollItem": {
            "type": "object",
            "properties": {
                "freq": {
                    "type": "integer"
                },
                "score": {
                    "type": "number"
                },
                "word": {
                    "type": "string"
                }
            }
        },
        "results.Collocations": {
            "type": "object",
            "properties": {
                "colls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mango.GoCollItem"
                    }
                },
                "concSize": {
                    "type": "integer"
                },
                "corpusSize": {
                    "type": "integer"
                },
                "error": {},
                "measure": {
                    "type": "string"
                },
                "srchRange": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "subcSize": {
                    "type": "integer"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MQuery API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
